services:
  - type: web
    name: twitter-event-detection-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/app.py
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
    healthCheckPath: /health

  - type: web
    name: twitter-event-detection-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    plan: free
    envVars:
      - key: REACT_APP_API_URL
        value: https://twitter-event-detection-backend.onrender.com
